port: 9000
nip11_pubkey: ~
nip11_contact: ~
nip11_description: custom relay for https://stemstr.app
nip11_version: 0.1
database_url: "postgresql://admin:password@localhost:5432/relay?sslmode=disable"
allowed_kinds: []
admins:
  admin: password
subscriptions_database_url: "postgresql://admin:password@localhost:6432/subscription?sslmode=disable"
blastr_nsec: "nsec1kk96g7rj34yfnyyjmgcjwa7kvjvddngxy2lwfx357w4lj8fnc20qpl0cr6"
bloom_filter_size: 1000000
bloom_filter_fp: 0.01
