port: 9000
nip11_pubkey: ~
nip11_contact: ~
nip11_description: custom relay for https://stemstr.app
nip11_version: 0.1
database_url: "postgresql://admin:password@localhost:5432/relay?sslmode=disable"
allowed_kinds: []
allowed_pubkeys: []
admins:
  admin: password
